config/routes.rb
Rails.application.routes.draw do
  get 'top/home'
  root 'top#home'
  get 'top/about'

  get 'session/new'
  post 'login', to: 'session#login'
  delete 'logout', to: 'session#logout'

  resources :users
  resources :post
  
  post 'post_detail/:id', to: 'post#create_detail', as: 'create_detail' 
  get 'post_confirm/:id', to: 'post#post_confirm', as: 'post_confirm'
  get 'post_viewing/:id', to: 'post#viewing', as: "viewing"

  get 'post_detail/edit/:id', to: 'post#detail_edit', as: 'detail_edit'
  patch 'post_detail/update/:id', to: 'post#detail_update',as: 'detail_update' 
  
  get 'detail_from_viewing/edit/:id', to: 'post#detail_edit_from_viewing', as: 'detail_edit_from_viewing'
  patch 'detail_from_viewing/update/:id', to: 'post#detail_from_viewing_update',as: 'detail_from_viewing_update' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/days_object.rb
class DaysObject < ApplicationRecord

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, class_name: "User",foreign_key: "user_id" 
  has_many :details, class_name: "PostDetail"
end

app/models/post_detail.rb
class PostDetail < ApplicationRecord
  
  belongs_to :post, class_name:"Post", foreign_key: "post_id"

  mount_uploader :detail_image, PostDetailImagesUploader

end

app/models/purpose_object.rb
class PurposeObject < ApplicationRecord

end

app/models/stay_object.rb
class StayObject < ApplicationRecord

end

app/models/total_money_object.rb
class TotalMoneyObject < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name,{presence: true}
  validates :email,{presence: true, uniqueness: true}
  has_many :post, class_name: "Post"

end

app/models/who_object.rb
class WhoObject < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionHelper
  include PostHelper
  include UsersHelper
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def new
    @post = Post.new

  end

  def create
    @post = Post.new(post_params)


    @post.user_id = session[:user_id]
    if @post.save
      redirect_to post_path(id: @post.id)
    else
      render :new
    end

  end

  def second
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
    @post_detail = PostDetail.new
    @made_post_detail = PostDetail.where(post_id: @post.id)
  end

  def create_detail
    @post = Post.find(params[:id])
    @user = User.find(@post.user_id)
    @post_detail = PostDetail.new(post_detail_params)
    @post_detail.post_id = @post.id 
    @post_detail.user_id = @post.user_id
  if @post_detail.save
    redirect_to post_path(id: @post.id)
  else
    render :show
  end
  end

  def post_confirm
    @post = Post.find(params[:id])
    @user = User.find(@post.user_id)
    @post_detail = PostDetail.find_by(post_id: @post.id)
    @made_post_detail = PostDetail.where(post_id: @post.id)
  end

  def viewing
    @post = Post.find(params[:id])
    @user = User.find(@post.user_id)
    @post_detail = PostDetail.find_by(post_id: @post.id)
    @made_post_detail = PostDetail.where(post_id: @post.id)
  end

  def detail_edit
    @post_detail = PostDetail.find(params[:id])
  end

  def detail_update
    @post_detail = PostDetail.find(params[:id])
    @post_detail.update(post_detail_params)
    if @post_detail.save
      redirect_to post_confirm_path(id: @post_detail.post_id)
    end
  end

  def detail_edit_from_viewing
    @post_detail = PostDetail.find(params[:id])
  end

  def detail_from_viewing_update
    @post_detail = PostDetail.find(params[:id])
    @post_detail.update(post_detail_params)
    if @post_detail.save
      redirect_to viewing_path(id: @post_detail.post_id)
    end
  end

  def edit
  end

  def index
  end

  private

  def post_params
    params.require(:post).permit(:title,:tag_id,:stay,:days,:who)
  end

  def post_detail_params
    params.require(:post_detail).permit(:name,:place,:purpose,:url,:hours_open,:hours_close,:comment,:detail_image,:cost)
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end


  def login
    user = User.find_by(email: params[:session][:email])
    if  user && user.authenticate(params[:session][:password])
        log_in user
        redirect_to user_path(user)
    else
        redirect_to new_user_path
        flash[:no_account] = "アカウントが見つかりません"

    end

  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def home
    @post = Post.all
    @details = PostDetail.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.user_image = "0.png"
    if @user.save
      redirect_to @user
      log_in @user

    end
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def update
    @user = User.find(session[:user_id])
    @user.name= params[:name]
    @user.account_name= params[:account_name]
    @user.email= params[:email]
    @user.comment= params[:comment]
    if params[:user_image]
      @user.user_image = "#{@user.id}.jpg"
      File.binwrite("public/user_images/#{@user.id}.jpg",params[:user_image].read)
    end
    if @user.save
      redirect_to @user
    else
      redirect_to root_path
    end
  end

  def show
    @user = User.find(session[:user_id])
    @post = Post.where(user_id: @user.id)
    current_user
    #@post_detail = PostDetail.where(post_id: @post.ids)
    #@post_detail = PostDetail.where(post_id: @post.ids) idsで合っているのか？
      #@post.each do |p|
        #@post_details = PostDetail.where(posr_id: p.id) 
      #end
  end

  def index
  end


  private

  def user_params
    params.require(:user).permit(:name,:account_name,:email,:comment,:password,:password_confirmation)
  end
  
  def update_params
    params.require(:user).permit(:name,:account_name,:email,:comment,:user_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/post_helper.rb
module PostHelper

  def time(object) 
    open_time = object.hours_open.hour
    close_time = object.hours_close.hour
    return "#{open_time}:#{close_time}"
  end

  def object_find(post)
    @who_object = WhoObject.find(post.who)
    @stay_object = StayObject.find(post.stay)
    @days_object = DaysObject.find(post.days)
    @total_money_object = TotalMoneyObject.find(post.total_money)
  end
end

app/helpers/session_helper.rb
module SessionHelper

  def log_in(user)
    session[:user_id] = user.id
  end


end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if(@user.id == session[:user_id])
      @current_user = @user
    end
  end



end

app/views/layouts/_header.html.erb
<div class="logo">
        <%= link_to 'Travel', root_path %>
      </div>  
        <div class="header-menus">
          <ul class="header-menu">
            <% if session[:user_id] %>  
              <li><%= link_to User.find(session[:user_id]).name, user_path(session[:user_id]) %></li>
              <li><%= link_to "ログアウト", logout_path, method: :delete  %></li>
              <li><%= link_to "新規投稿", new_post_path %></li>
            <% else %>  
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                ログイン <b class="caret"></b>
                </a>
                <div class="dropdown-menu">
                  <div class="dropdown-login">
                    <%= form_for(:session, url: login_path) do |f| %>
  
                      <%= f.label :"メールアドレス" %>
                      <%= f.text_field :email, class: "form-control" %>

                      <%= f.label :"パスワード" %>
                      <%= f.password_field :password, class: "form-control" %>

                      <%= f.submit "ログイン", class: "login-btn" %>
            
                    <% end %>
                  </div>  
                </div>
              </li>
              <li><%= link_to "新規登録" , new_user_path %></li>
              <li><%= link_to "検索" , root_path %></li>
            <% end %>  
          </ul>
          
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OriginalApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>  
    </header>
    <%= yield %>
  </body>
</html>

app/views/post/_form.html.erb
<%= form_for @post_detail, url:{controller: :post, action: :create_detail} do |f| %>
  <div class="detail-form">
    <div class="post-detail">
      <div class="post-num">
        <p>1</p>
      </div>
      <div class="post-etc">

        <div class="post-purpose post-info">
          <p>目的<br>
          <%= f.select :purpose, {'観光': '観光',  '宿泊': '宿泊', '食事': '食事', '休憩': '休憩', 'スポーツ': 'スポーツ', '移動': '移動', '自然': '自然', '買い物': '買い物'}, { required: true } %>
        </div>

        <div class="post-place post-info">
          <p>訪れた場所の名前：</p>
          <%= f.text_field :name %>
          </div>

        <div class="post-address post-info">
          <p>住所：</p>
          <%= f.text_field :place %>
        </div>

        <div class="post-url post-info">
          <p>URL：</p>
          <%= f.text_field :url %>
        </div>

        <div class="post-hours post-info">
          <p>営業時間：</p>
          <p>開始時間：<%= f.time_select :hours_open, { required: true } %></p>
          <p>終業時間：<%= f.time_select :hours_close, { required: true } %></p>
        </div>

        <div class="post-info post-cost">
          <p>かかる金額：</p>
          <div class="cost">
            <%= f.text_field :cost %>
            <p>円</p>
          </div>  
        </div>

        <div class="post-comment">
          <p>コメント：</p>
          <%= f.text_area :comment %>
        </div>
        <div>
          <p>この旅行の写真：</p>
          <%= f.file_field :detail_image,value: "0.jpg" %>
        </div>
        <div class="detail-form-btn">
          <%= f.submit "追加する", :name=>"add" %>
        <div>
      </div>
    </div>
  </div>
<% end %>

app/views/post/detail_edit.html.erb
<div class="second-form">


      <div class="made-detail">
      <p>現在の投稿</p>
          <div class="made-detail-inner">
          <div class="made-detail-left">
             <div class="detail-image">
               <img src = "<%="#{@post_detail.detail_image}"%>" class= "detail_img">
             </div>
          </div>
          <div class="made-detail-right">
            <div class="made-detail-purpose">
            <p>目的：<%= @post_detail.purpose %></p></div>
            <div class="made-detail-name"><p>訪れた場所：<%= @post_detail.name %></p></div>
            <div class="made-detail-url"><p>参考URL：<%= link_to "詳しくはこちら", @post_detail.url, target: :_blank %></p></div>
            <div class="made-detail-place"><p>場所：<%= @post_detail.place %></p></div>
            <div class="made-detail-hours"><p>営業時間：

            <% if @post_detail.hours_open.hour != 0 %>
              <%= @post_detail.hours_open.hour %> :
            <% else %>
              00 :
            <% end %>

            <% if @post_detail.hours_open.min != 0 %>
              <%= @post_detail.hours_open.min %>から
            <% else %>
              00から
            <% end %>
                    
            <% if @post_detail.hours_close.hour != 0 %>
              <%= @post_detail.hours_close.hour %> :
            <% else %>
              00 :
            <% end %>  
            
            <% if @post_detail.hours_close.min != 0 %>
              <%=  @post_detail.hours_close.min %>まで
            <% else %>  
              00まで
            <% end %>
            
            </p></div>
            <div><p>コメント：<%= @post_detail.comment %></p></div>
          </div>  
        </div>  
      </div>

</div>

<%= form_for @post_detail, url:{controller: :post, action: :detail_update} do |f| %>
  <div class="detail-form">
    <div class="post-detail">
      <div class="post-num">
        <p>1</p>
      </div>
      <div class="post-etc">
        <div class="post-purpose post-info">
          <p>目的<br>
          <%= f.select :purpose, {'観光': 1,  '宿泊': 2, '食事': 3, '休憩': 4, 'スポーツ': 5, '移動': 6, '自然': 7, '買い物': 8}, { required: true } %>
        </div>
        <div class="post-place post-info">
          <p>訪れた場所の名前：</p>
          <%= f.text_field :name %>
          </div>
        <div class="post-address post-info">
          <p>住所：</p>
          <%= f.text_field :place %>
        </div>
        <div class="post-url post-info">
          <p>URL：</p>
          <%= f.text_field :url %>
        </div>
        <div class="post-hours post-info">
          <p>営業時間：</p>
          <p>開始時間：<%= f.time_select :hours_open, { required: true } %></p>
          <p>終業時間：<%= f.time_select :hours_close, { required: true } %></p>
        </div>
        <div class="post-comment">
         <p>コメント：</p>
          <%= f.text_area :comment %>
        </div>
        <div>
          <p>この旅行の写真：</p>
          <%= f.file_field :detail_image %>
        </div>
        <div class="detail-form-btn">
        <%= f.submit "上記の内容で修正する" %>
        <div>
      </div>
    </div>
  </div>
<% end %>

app/views/post/detail_edit_from_viewing.html.erb
<div class="second-form">


      <div class="made-detail">
      <p>現在の投稿</p>
          <div class="made-detail-inner">
          <div class="made-detail-left">
             <div class="detail-image">
                <% if @post_detail.detail_image %>
                  <img src = "<%="#{@post_detail.detail_image}"%>" class= "detail_img">
                <% else %>
                  <img src = "<%="/user_image/0.png"%>" class= "detail_img">
                <% end %>  
             </div>
          </div>
          <div class="made-detail-right">
            <div class="made-detail-purpose">
            <p>目的：<%= @post_detail.purpose %></p></div>
            <div class="made-detail-name"><p>訪れた場所：<%= @post_detail.name %></p></div>
            <div class="made-detail-url"><p>参考URL：<%= link_to "詳しくはこちら", @post_detail.url, target: :_blank %></p></div>
            <div class="made-detail-place"><p>場所：<%= @post_detail.place %></p></div>
            <div class="made-detail-hours"><p>営業時間：

            <% if @post_detail.hours_open.hour != 0 %>
              <%= @post_detail.hours_open.hour %> :
            <% else %>
              00 :
            <% end %>

            <% if @post_detail.hours_open.min != 0 %>
              <%= @post_detail.hours_open.min %>から
            <% else %>
              00から
            <% end %>
                    
            <% if @post_detail.hours_close.hour != 0 %>
              <%= @post_detail.hours_close.hour %> :
            <% else %>
              00 :
            <% end %>  
            
            <% if @post_detail.hours_close.min != 0 %>
              <%=  @post_detail.hours_close.min %>まで
            <% else %>  
              00まで
            <% end %>
            
            </p></div>
            <div><p>コメント：<%= @post_detail.comment %></p></div>
          </div>  
        </div>  
      </div>

</div>

<%= form_for @post_detail, url:{controller: :post, action: :detail_from_viewing_update} do |f| %>
  <div class="detail-form">
    <div class="post-detail">
      <div class="post-num">
        <p>1</p>
      </div>
      <div class="post-etc">
        <div class="post-purpose post-info">
          <p>目的<br>
          <%= f.select :purpose, {'観光': 1,  '宿泊': 2, '食事': 3, '休憩': 4, 'スポーツ': 5, '移動': 6, '自然': 7, '買い物': 8}, { required: true } %>
        </div>
        <div class="post-place post-info">
          <p>訪れた場所の名前：</p>
          <%= f.text_field :name %>
          </div>
        <div class="post-address post-info">
          <p>住所：</p>
          <%= f.text_field :place %>
        </div>
        <div class="post-url post-info">
          <p>URL：</p>
          <%= f.text_field :url %>
        </div>
        <div class="post-hours post-info">
          <p>営業時間：</p>
          <p>開始時間：<%= f.time_select :hours_open, { required: true } %></p>
          <p>終業時間：<%= f.time_select :hours_close, { required: true } %></p>
        </div>
        <div class="post-comment">
         <p>コメント：</p>
          <%= f.text_area :comment %>
        </div>
        <div>
          <p>この旅行の写真：</p>
          <%= f.file_field :detail_image %>
        </div>
        <div class="detail-form-btn">
        <%= f.submit "上記の内容で修正する" %>
        <div>
      </div>
    </div>
  </div>
<% end %>

app/views/post/index.html.erb
<h1>Post#index</h1>
<p>Find me in app/views/post/index.html.erb</p>

app/views/post/new.html.erb
<%= form_for @post, url: post_index_path do |f| %>
  <div class="post-new-form">
    <div class="post-new-form-inner">
      <h1>旅のしおりを作る</h1>
      <div class = "post-main">

        <div class="post-main-left">
          <div class="post-title">
            <%= f.label :"投稿タイトル:" %>
            <%= f.text_field :title, class: 'input-form' %>
          </div>  
          <div class="post-tag">
             <%= f.label :"タグ:" %>
            <%= f.text_field :tag_id, class: 'input-form' %>
          </div>
        </div>

      <div class="post-main-right">
        <div class="post-days">
          <p>宿泊日数：<br>
          <%= f.select :stay, {'1泊': "1泊",  '2泊': "2泊", '3泊': "3泊", '4泊': "4泊", '5泊': "5泊", '6泊': "6泊", '7泊': "7泊"}, { required: true } %>
          <%= f.select :days, {"1日": "1日", "2日": "2日", "3日": "3日", "4日": "4日", "5日": "5日", "6日": "6日", "7日": "7日", "8日": "8日"}, { required: true } %>
          </p>
        </div >
        <div class="post-who">
          <p>誰との旅行：<br>
            <%= f.select :who, {"ひとり": "ひとり", "友達(2人)": "友達(2人)", "友達(3人以上)": "友達(3人以上)", "カップル": "カップル", "夫婦": "夫婦", "家族": "家族"},{reqired: true} %>
        </div>
        
      </div>

    </div>
  
  </div>
  <div class="post-form-btn">
    <%= f.submit "次へ" %>
  </div>

</div>

<% end %>

app/views/post/post_confirm.html.erb
<div class="second-form">
    <div class="second-form-inner">
      <h1>旅のしおりを作る</h1>
      <div class = "second-post-main">

        <div class="second-post-main-left">
          <div class="second-title">
           <p>旅行タイトル：
           <%= @post.title %>
           </p>
          </div>  
          <div class="second-tag">
            <p>タグ：</p>
            <h3><%= @post.tag_id  %></h3>
          </div>
        </div>
        

        <div class="second-post-main-right">
          <div class="second-days">
            <p>宿泊日数: <%=  @post.stay %><%= @post.days %></p>
          </div >
          <div class="secons-who">
            <p>誰との旅行：<%= @post.who %></p>
          </div>
          <div>
            <p>合計金額：<%= @post.details.sum(:cost) %>円</p>
          </div>
        </div>

      </div>
      <% if @create_detail %>
      <% end %>
  
    </div>

    <% if @made_post_detail %>
      <% @made_post_detail.each.with_index(1) do |f,i| %>
      <div class="made-detail">
          <div class="made-detail-inner">
          <div class="made-detail-left">
             <div class="detail-image">
               <img src = "<%="#{f.detail_image}"%>" class= "detail_img">
             </div>
          </div>
          <div class="made-detail-right">
            <p class="detail-num"><%= i %></p>
            <div class="made-detail-purpose">
            <p>目的：<%= f.purpose %></p></div>
            <div class="made-detail-name"><p>訪れた場所：<%= f.name %></p></div>
            <div class="made-detail-url"><p>参考URL：<%= link_to "詳しくはこちら", f.url, target: :_blank %></p></div>
            <div class="made-detail-place"><p>場所：<%= f.place %></p></div>
            <div class="made-detail-hours"><p>営業時間：

            <% if f.hours_open.hour != 0 %>
              <%= f.hours_open.hour %> :
            <% else %>
              00 :
            <% end %>

            <% if f.hours_open.min != 0 %>
              <%= f.hours_open.min %>から
            <% else %>
              00から
            <% end %>
                    
            <% if f.hours_close.hour != 0 %>
              <%= f.hours_close.hour %> :
            <% else %>
              00 :
            <% end %>  
            
            <% if f.hours_close.min != 0 %>
              <%=  f.hours_close.min %>まで
            <% else %>  
              00まで
            <% end %>
            
            </p></div>
            <div class="made-detail-cost"><p>かかった金額：<%= f.cost %>円</p></div>
            <div><p>コメント：<%= f.comment %></p></div>
          </div>  
        </div>  
        <div class="detail-edit"><%= link_to "修正する", detail_edit_path(id: f.id) , class: "detail-edit-btn" %></div>
      </div>

      <% end %>
      <div class="confirm-btn">
        <div class="finish-edit">
          <%= link_to "完成", user_path , class: "finish-edit-btn" %>
        </div>
        <div class="return-post-make">
          <%= link_to "更に追加する", post_path(@post) , class: "return-btn" %>
        </div>
      </div>  
    <% end %>  

</div>

app/views/post/viewing.html.erb
<div class="second-form">
    <div class="viewing-prof">
      <img src = "<%="/user_images/#{@post.user.user_image}"%>" class= "viewing-user-img">
      <div class="viewing-user-name">
        <p><%= link_to "#{ @post.user.name }", user_path ,class: "v-user-name" %>　さんの投稿ページ</p>
      </div>  

    </div>
    <div class="second-form-inner">
      <h1></h1>
      <div class = "second-post-main">

        <div class="second-post-main-left">
          <div class="second-title">
           <p>旅行タイトル：
           <%= @post.title %>
           </p>
          </div>  
          <div class="second-tag">
            <p>タグ：</p>
            <h3><%= @post.tag_id  %></h3>
          </div>
        </div>
        

        <div class="second-post-main-right">
          <div class="second-days">
            <p>宿泊日数: <%=  @post.stay %><%= @post.days %></p>
          </div >
          <div class="secons-who">
            <p>誰との旅行：<%= @post.who %></p>
          </div>
          <div>
            <p>合計金額：<%= @post.details.sum(:cost) %>円</p>
          </div>
        </div>

      </div>
      <% if @create_detail %>
      <% end %>
  
    </div>

    <% if @made_post_detail %>
      <% @made_post_detail.each.with_index(1) do |f,i| %>
      <div class="made-detail">
          <div class="made-detail-inner">
          <div class="made-detail-left">
             <div class="detail-image">
              <% if f.detail_image? %>
                <img src = "<%="#{f.detail_image}"%>" class= "detail_img">
              <% else %>
                <img src = "/user_images/0.png" class= "detail_img">
              <% end %>    
             </div>
          </div>
          <div class="made-detail-right">
            <p class="detail-num"><%= i %></p>
            <div class="made-detail-purpose">
            <p>目的：<%= f.purpose %></p></div>
            <div class="made-detail-name"><p>訪れた場所：<%= f.name %></p></div>
            <div class="made-detail-url"><p>参考URL：<%= link_to "詳しくはこちら", f.url, target: :_blank %></p></div>
            <div class="made-detail-place"><p>場所：<%= f.place %></p></div>
            <div class="made-detail-hours"><p>営業時間：

            <% if f.hours_open.hour != 0 %>
              <%= f.hours_open.hour %> :
            <% else %>
              00 :
            <% end %>

            <% if f.hours_open.min != 0 %>
              <%= f.hours_open.min %>から
            <% else %>
              00から
            <% end %>
                    
            <% if f.hours_close.hour != 0 %>
              <%= f.hours_close.hour %> :
            <% else %>
              00 :
            <% end %>  
            
            <% if f.hours_close.min != 0 %>
              <%=  f.hours_close.min %>まで
            <% else %>  
              00まで
            <% end %>
            
            </p></div>
            <div class="made-detail-cost"><p>かかった金額：<%= f.cost %>円</p></div>
            <div><p>コメント：<%= f.comment %></p></div>
          </div>  
        </div>  
        <% if( session[:user_id] == Post.find(params[:id]).user.id ) %>
          <%= link_to "修正する", detail_edit_from_viewing_path(f.id) %>
        <% end %>
      </div>
      
      <% end %>
    <% end %>  
    <div class="go-user-page">
      <%= link_to "#{ @post.user.name }　さんのページに戻る", user_path ,class: "v-user-name" %>
    </div>  
</div>

app/views/top/home.html.erb
<div class="home-post">
  <% @post.order("id DESC").each do |f| %>
    <div class="home-post-inner">
      <div class="home-up">
        <div class="home-upper">
          <div class="home-prof-img">
            <%= link_to (image_tag "/user_images/#{f.user.user_image}"), user_path(f.user.id) %>
          </div>
          <div class="home-name">
            <%= f.user.name %>
          </div>  
        </div>  
        <div class="home-created-at">
          <p><%= f.created_at.month %>月<%= f.created_at.day %>日に作られた投稿</p>
        </div>
      </div>  
      <div class="home-detail-image">
      <% f.details.first(4).each do |d| %>
        <% if d.detail_image? %>      
          <%= link_to (image_tag "#{d.detail_image}"), viewing_path(d.post.id) %>
        <% else %>
          <%= link_to (image_tag "/user_images/0.png"), viewing_path(d.post.id) %> 
        <% end %>   
      <% end %>
      </div>
    </div>
  <% end %>    
</div>  

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<div class="user-info">
  
  <div class="user-self-info">
    <div class="info-left">
      <img src = "<%="/user_images/#{@user.user_image}"%>" class= "user_img">
    </div>
    <div class="info-right">
      <div class="info-right-name"><h1 class="info-name"><%= @user.name %></h1>
      </div>
      <div class="info-right-num">
        <h3 class="info-account-name"><%= @user.account_name %></h3>
        <div class="follow">
          <h3 class="a">___フォロー中</h3>
          <h3 class="b">___フォロワー</h3>
        </div>
      </div>  
      <div class="profile-text"><%= @user.comment %></div>
    </div>
    <div class="info-rr">
      <%= link_to '編集', edit_user_path(id: @user.id) ,class:"info-edit" %>
    </div>

  </div>  
  <% @user.post.each do |f| %>
    <div class="user-travel-info">
    
      
        <div class="user-travel-left">  
          <div class="detail-img-box">
            <% f.details.first(4).each do |d| %>
              <div class="user-detail-img">
                <% if d.detail_image? %>
                  <%= link_to (image_tag "#{d.detail_image}"), viewing_path(f.id) %>
                <% else %>
                  <%= link_to (image_tag "/user_images/0.png"), viewing_path(f.id) %>
                <% end %>  
              </div>  
            <% end %>
          </div>
        </div>
    
        <div class="user-travel-right">  

          <div class="travel-title">
            <p>旅行タイトル：<%= f.title %></p>
          </div>
          <div class="travel-days">
            <p>宿泊日数：<%= f.stay %><%= f.days %></p>
          </div>  
          <div class="travel-who">
            <p>誰と：<%= f.who %></p>
          </div>
          <div class="travel-cost">
            <p>合計予算：<%= f.details.sum(:cost) %>円</p>
          </div>
          <div class="travel-like">
            <p>___　いいね　　___コメント</p>
          </div>

        </div> 
    </div>  
  <% end %>
</div>  